### ISSUE TITLE
Compile error when using KDBindings in combination with Qt

### ISSUE THREAD

**Issue by AndreasSchacherbauer** [KDAB/KDBindings#79] opened 2024-06-13 09:12 UTC
Hi!
I wanted to use KSBindings in a project where I also use Qt. At a certain point I needed to include kdbindings/signal.h as well as QObject. This then results in a compile error (on gcc as well as clang). As I investigated further it turned out that the order of includes matter. If KDBindings is included first, it works. If QObject is first then it doesn’t.
I was surprised and wanted to ask if this is a known limitation.

The compile error looks like the following:

```
[  9%] Building CXX object CMakeFiles/workshop_episode_001.dir/src/Translator.cpp.o
In file included from src/Translator.cpp:3:
In file included from include/IResourceManager.hpp:3:
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:285:23: error: expected ')'
        void emit(Args... p) const
                      ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:285:18: note: to match this '('
        void emit(Args... p) const
                 ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:285:19: error: declaration of 'Args' shadows template parameter
        void emit(Args... p) const
                  ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:213:22: note: template parameter is declared here
template<typename... Args>
                     ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:285:19: error: field has incomplete type 'void'
        void emit(Args... p) const
                  ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:285:29: error: expected ';' at end of declaration list
        void emit(Args... p) const
                            ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:308:49: error: use of undeclared identifier 'Connection'
        mutable Private::GenerationalIndexArray<Connection> m_connections;
                                                ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:488:19: error: expected ')'
    void emit(Args... p) const
                  ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:488:14: note: to match this '('
    void emit(Args... p) const
             ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:488:15: error: declaration of 'Args' shadows template parameter
    void emit(Args... p) const
              ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:213:22: note: template parameter is declared here
template<typename... Args>
                     ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:488:15: error: field has incomplete type 'void'
    void emit(Args... p) const
              ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:488:25: error: expected ';' at end of declaration list
    void emit(Args... p) const
                        ^
conan_cache/.conan/data/kdbindings/1.0.1/conan_toolchain_catalog/build/package/e7a4df623f2f69d6974a12334b94709d4f79466f/include/kdbindings/signal.h:259:13: error: unknown type name 'Connection'
            Connection *connection = m_connections.get(id);
            ^
10 errors generated.
make[3]: *** [CMakeFiles/workshop_episode_001.dir/build.make:161: CMakeFiles/workshop_episode_001.dir/src/Translator.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1247: CMakeFiles/workshop_episode_001.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1254: CMakeFiles/workshop_episode_001.dir/rule] Error 2
make: *** [Makefile:712: workshop_episode_001] Error 2 
```

**Comment by seanharmer** [comment] 2024-06-13 12:42
Hi, thanks for the report. This looks like it is caused by the way Qt implments the `emit` "keyword" which is to actually #define it to nothing. This means that in Qt you can do `emit mySignal()` which boils down to a simple function call to `mySignal()` as implemented by the moc.

With this in mind, it makes sense that at present the include order of the headers matters as if the Qt header is included first our `void emit(Args... p) const;` function in Signal becomes `void (Args... p) const;` when the compiler sees it.

For now, including `kdbindings/signal.h` first is the correct work around.

We will look at adding some check to see if `emit` is defined and warn in that case. Or perhaps we will make the `emit()` function name configurable to be able to avoid such conflicts.

I will leave this issue open until we get something in place.

**Comment by seanharmer** [comment] 2024-06-13 12:43
One other thing to consider is the QT_NO_KEYWORDS macro which stops Qt from defining these keywords.

**Comment by AndreasSchacherbauer** [comment] 2024-06-13 14:22
Thanks, @seanharmer! Defining `QT_NO_EMIT` works perfectly.
Would it be an option for you to add an CMake option to KDBindings to add something like `target_compile_definitions(KDBindings PUBLIC QT_NO_EMIT)`? Not sure how evil that is for other users, but if it could be optionally enabled it might not hurt. And I don’t need to deal with it in all my projects 😆

thx again for the quick reply!

**Comment by seanharmer** [comment] 2024-06-13 15:10
I'll leave it up to @LeonMatthesKDAB but perhaps that could be part of a Qt compatibility option.

**Comment by LeonMatthesKDAB** [comment] 2024-06-14 12:38
Hi @AndreasSchacherbauer thank you for reporting this issue.

I've added `KDBindings_QT_NO_EMIT` in #82 . Can you confirm that enabling this option indeed solves your issue?
For now this is disabled by default, as this will likely break a lot of stuff for existing Qt codebases if added without notice.

**Comment by LeonMatthesKDAB** [comment] 2024-07-02 11:47
Closing this for now, please re-open if the solution in #82 is not sufficient

**Closed by LeonMatthesKDAB** 2024-07-02 11:47 UTC
